### ISSUE TITLE
Doesn't work pkcs#11 with Securemetric ST3 Token

### ISSUE THREAD

**Issue by r0otsharp** [risacher/putty-cac#10]
Hi

I want to Setup PKCS#11 Settings. but after set PKSC#11 Library your software show list of token. then select token when leave token label and set certificate label token label automatically clear and certificate label is empty. please help me.
when i again select token label show E: NO SLOTS FOUND!
Best Regards
Ehsan Farahani

**Comment by risacher** [comment]
Since the PKCS#11 support has been removed from the most recent version of PuTTY-CAC, I'm closing this issue.
