### ISSUE TITLE
Putty-cac and SSH certificates

### ISSUE THREAD

**Issue by avivzl** [risacher/putty-cac#11]
Hi,

Putty CAC works great with public keys. As far as I understand I take out the public key out of the user certificate (from the token) and put it into the SSH authoruzed_keys. So far so good.

Suppose I want to use SSH certificates. in this scenario I usually put the public key of the CA  into the server and then use my public certificate (instead of my public key)  and my private key to log into the server. This also work great with openssh.

I tried to do this with Putty-cac:
I put the CA public key in the server and tried to log in with my smartcard via putty-cac, but it doesn't work.

Is there a way to do this with putty-cac?

Thanks.

**Comment by NoMoreFood** [comment]
Closing again.  Looks like a mistaken reference to this via PKCS reopened this.
