### ISSUE TITLE
Add support for newer Message Authentication Code

### ISSUE THREAD

**Issue by risacher** [risacher/putty-cac#14]
User report: ...our systems are secured to adhere to a higher
MAC - Message Authentication Code

Our severs are configured to only support:

    hmac-ripemd160,hmac-sha2-256,hmac-sha2-512

The Putty-CAC only suports:

    hmac-sha1,hmac-sha1-96,hmac-md5

**Comment by risacher** [comment]
According to http://ssh-comparison.quendi.de/impls/putty.html, putty supports hmac-sha2-256

**Comment by IMAI-Yuji** [comment]
Checking putty event log, Putty-CAC selects hmac-sha2-256 between OpenSSH6.7p1 Debian-5.

![putty-negotiation](https://cloud.githubusercontent.com/assets/1840560/12085401/2968808c-b303-11e5-82a0-58d38a706df6.png)

**Comment by risacher** [comment]
@IMAI-Yuji Thank you.
