### ISSUE TITLE
Clicking "Remove key" in Pageant without any key selected, crashes the application

### ISSUE THREAD

**Issue by LordMike** [risacher/putty-cac#17]
As the title says.

However, this last time when I wanted to grab a screenshot - suddenly it doesn't happen?
It's happened every time I tested it up until now though. 

Version was just downloaded today from http://risacher.org/putty-cac/, but the "File Version" is 0.0.0.0

**Comment by IMAI-Yuji** [comment]
On my environment, it doesn't happen with a pagent 0.66-sync ( https://github.com/risacher/putty-cac/tree/0.66-sync/executables/pageant.exe?raw=true ). Does it still crashed, @LordMike ?

**Comment by LordMike** [comment]
I have been unable to reproduce it since. Both in the past versions and the current.

**Comment by IMAI-Yuji** [comment]
Glad to hear it. :four_leaf_clover:
