### ISSUE TITLE
putty 0.66

### ISSUE THREAD

**Issue by jotpe** [risacher/putty-cac#19]
New upstream version with a security fix available.

**Comment by risacher** [comment]
Should be fixed by branch "0.66-sync".  Will merge into master after I get some feedback that it works.

**Comment by IMAI-Yuji** [comment]
I checked they works fine in following use-cases.

Target: https://github.com/risacher/putty-cac/tree/0.66-sync/executables
Environment: Windows 7 (64bit)

* putty.exe
 * SSH login with my PKCS-11 by CAPI.
* pageant.exe
 * putty, teraterm, winscp
 * agent forwarding with ssh(1), git(1) 
 * Execute with a fingerprint argument while booting up Windows.
