### ISSUE TITLE
Google Chrome reports site as "Dangerous"

### ISSUE THREAD

**Issue by teridon** [risacher/putty-cac#21]
When I visit risacher.org, Google Chrome reports that the site is harmful.

see  [this report](https://www.google.com/transparencyreport/safebrowsing/diagnostic/index.html?hl=en-US#url=https://www.risacher.org/putty-cac/)

The "status" of the site is: "Dangerous:  www.risacher.org/putty-cac contains harmful programs."

**Comment by risacher** [comment]
Deleted old versions and asked google to rescan.  Google's security console said "Unspecified malware" and listed zero offending links.  Grr.
