### ISSUE TITLE
Windows 10 Compatibility

### ISSUE THREAD

**Issue by giesberge** [risacher/putty-cac#25]
Can't seem to get it to run successfully in Windows 10, official upstream works fine though. This might be more of an issue since I think they're trying to convert everyone over to Windows 10 soonish.

**Comment by jdantzler** [comment]
I have it running fine with CAPI support on Windows 10.  I have tested version 0.67, 0.66, and 0.65 and all seem to work on my end.  I haven't noticed any issues thus far.  Can you please describe in more detail what the problem is and the steps to reproduce the issue?  Thanks.

**Comment by giesberge** [comment]
Can't replicate it, I think it was something weird with how I was downloading it from Github, seems to be working fine.
