### ISSUE TITLE
PKCS#11 support

### ISSUE THREAD

**Issue by Ocup** [risacher/putty-cac#26]
as stated [here](https://risacher.org/putty-cac/)
i would request PKCS11 support for the latest version and compile with latest visual studio and keep Windows XP compatibility.
I currently use [putty-vx4-bin](http://blog.vx4.de/~ck/blog/articles/128/putty-vx4-bin) but bin are outdated.
Or make available older release putty-CAC 0.62 with pkcs#11 support and Windows XP compatibility.

**Comment by jdantzler** [comment]
The older version of PuTTY-CAC 0.62 does support PKCS#11 and I believe it will work with XP, but not 100% sure.  I have uploaded the older version below.  I hope this helps.

[PuTTY-CAC 0.62.zip](https://github.com/risacher/putty-cac/files/199471/PuTTY-CAC.0.62.zip)

**Comment by NoMoreFood** [comment]
@Ocup If still interested, please see this conversation.  https://github.com/NoMoreFood/putty-cac/issues/1.

**Comment by NoMoreFood** [comment]
These changes have made their way into PuTTY CAC 0.68 Update 2 Pre-Release.  Closing this out.  If you have any problems with the pre-release, please create a new issue.
