### ISSUE TITLE
putty-cac and OpenSSH

### ISSUE THREAD

**Issue by sumit-bose** [risacher/putty-cac#28]
Hi,

I'm trying to connect with putty-cac to a OpenSSH server. For some certificates it is working as expected but for some it fails with messages like 

`May 17 17:14:07 sssd-devel sshd[651]: error: buffer_get_bignum2_ret: negative numbers not supported [preauth]`

It looks like putty-cac and OpenSSH's ssh-keygen generate slightly different public keys:

putty-cac:
echo -n AAAAB3NzaC1yc2EAAAAEsSwzJwAAAQEAg998ayLmHJMQsH7TZDXTrcXx8tS8ZnBe0GU5/v2Ghyggk5N/uJrMJSDu/pidlQ4rmAWtSySjGtMvB0FEofL74+lBZmTS1nEQGHfyiv3Fa6+9+AH4SDWWV341rcrVKis1ZMlRFRVIhsudmcgC2e69O7qSJ+ms52oFGL0sacY9d9UKV/NKgVD/dkXb7f03NCj7dVZVHauZxBmPv2FpFKa55PkSr9hQB4dLarjuh7B5Em+Lg4+tRUZop4kNooeo/P/WsWNNefZWjpwOQ1IklKnHhdGBPIE5a5NQQoXeacyGtybN9M9SBJCdIBW4CAbQBa5VNI3mjs/rlxTHO2dDaSmcHQ== |base64 -d | od -t x1  
0000000 00 00 00 07 73 73 68 2d 72 73 61 00 00 00 04 b1
0000020 2c 33 27 00 00 01 01 00 83 df 7c 6b 22 e6 1c 93
0000040 10 b0 7e d3 64 35 d3 ad c5 f1 f2 d4 bc 66 70 5e
0000060 d0 65 39 fe fd 86 87 28 20 93 93 7f b8 9a cc 25
0000100 20 ee fe 98 9d 95 0e 2b 98 05 ad 4b 24 a3 1a d3
0000120 2f 07 41 44 a1 f2 fb e3 e9 41 66 64 d2 d6 71 10
0000140 18 77 f2 8a fd c5 6b af bd f8 01 f8 48 35 96 57
0000160 7e 35 ad ca d5 2a 2b 35 64 c9 51 15 15 48 86 cb
0000200 9d 99 c8 02 d9 ee bd 3b ba 92 27 e9 ac e7 6a 05
0000220 18 bd 2c 69 c6 3d 77 d5 0a 57 f3 4a 81 50 ff 76
0000240 45 db ed fd 37 34 28 fb 75 56 55 1d ab 99 c4 19
0000260 8f bf 61 69 14 a6 b9 e4 f9 12 af d8 50 07 87 4b
0000300 6a b8 ee 87 b0 79 12 6f 8b 83 8f ad 45 46 68 a7
0000320 89 0d a2 87 a8 fc ff d6 b1 63 4d 79 f6 56 8e 9c
0000340 0e 43 52 24 94 a9 c7 85 d1 81 3c 81 39 6b 93 50
0000360 42 85 de 69 cc 86 b7 26 cd f4 cf 52 04 90 9d 20
0000400 15 b8 08 06 d0 05 ae 55 34 8d e6 8e cf eb 97 14
0000420 c7 3b 67 43 69 29 9c 1d
0000430

ssh-keygen:
echo -n AAAAB3NzaC1yc2EAAAAFALEsMycAAAEBAIPffGsi5hyTELB+02Q1063F8fLUvGZwXtBlOf79hocoIJOTf7iazCUg7v6YnZUOK5gFrUskoxrTLwdBRKHy++PpQWZk0tZxEBh38or9xWuvvfgB+Eg1lld+Na3K1SorNWTJURUVSIbLnZnIAtnuvTu6kifprOdqBRi9LGnGPXfVClfzSoFQ/3ZF2+
39NzQo+3VWVR2rmcQZj79haRSmueT5Eq/YUAeHS2q47oeweRJvi4OPrUVGaKeJDaKHqPz/1rFjTXn2Vo6cDkNSJJSpx4XRgTyBOWuTUEKF3mnMhrcmzfTPUgSQnSAVuAgG0AWuVTSN5o7P65cUxztnQ2kpnB0= |base64 -d | od -t x1
0000000 00 00 00 07 73 73 68 2d 72 73 61 00 00 00 05 00
0000020 b1 2c 33 27 00 00 01 01 00 83 df 7c 6b 22 e6 1c
0000040 93 10 b0 7e d3 64 35 d3 ad c5 f1 f2 d4 bc 66 70
0000060 5e d0 65 39 fe fd 86 87 28 20 93 93 7f b8 9a cc
0000100 25 20 ee fe 98 9d 95 0e 2b 98 05 ad 4b 24 a3 1a
0000120 d3 2f 07 41 44 a1 f2 fb e3 e9 41 66 64 d2 d6 71
0000140 10 18 77 f2 8a fd c5 6b af bd f8 01 f8 48 35 96
0000160 57 7e 35 ad ca d5 2a 2b 35 64 c9 51 15 15 48 86
0000200 cb 9d 99 c8 02 d9 ee bd 3b ba 92 27 e9 ac e7 6a
0000220 05 18 bd 2c 69 c6 3d 77 d5 0a 57 f3 4a 81 50 ff
0000240 76 45 db ed fd 37 34 28 fb 75 56 55 1d ab 99 c4
0000260 19 8f bf 61 69 14 a6 b9 e4 f9 12 af d8 50 07 87
0000300 4b 6a b8 ee 87 b0 79 12 6f 8b 83 8f ad 45 46 68
0000320 a7 89 0d a2 87 a8 fc ff d6 b1 63 4d 79 f6 56 8e
0000340 9c 0e 43 52 24 94 a9 c7 85 d1 81 3c 81 39 6b 93
0000360 50 42 85 de 69 cc 86 b7 26 cd f4 cf 52 04 90 9d
0000400 20 15 b8 08 06 d0 05 ae 55 34 8d e6 8e cf eb 97
0000420 14 c7 3b 67 43 69 29 9c 1d
0000431

As you can see the key are nearly the same expect that the exponent is prefixed by '00' in the ssh-keygen case because the exponent starts with 'b1' which would indicate a negative number to bigint.

I think capi_get_pubkey_blob() should be enhanced to add a leading zero to the exponent part of the key as it already does for the modulus.

I think I can provide a patch but I'm not sure if I will be able to build putty-cac on Windows.

**Comment by NoMoreFood** [comment]
@sumit-bose Can you validate this is still a problem with the PuTTY 0.68 Update 1 release?  If so, can you possibly email me your sshd_config file and the version of SSH server you are using?

**Comment by NoMoreFood** [comment]
@sumit-bose Due to the lack of response, I'm going to close this out.  If you want to continue to investigate this, please ensure the problem still exists in PuTTY CAC 0.68 Update 2 Pre-Release and then we can reopen or create a new issue.
