### ISSUE TITLE
SHA checksums for the executables

### ISSUE THREAD

**Issue by thywyn** [risacher/putty-cac#29]
Would like to have checksums (SHA1 or SHA256 preferably) for the binary downloads.

**Comment by NoMoreFood** [comment]
@thywyn I'm awaiting a code signing certificate so I'll publish SHA256 / MD5 hashes once I release a signed version.  Probably a week or two.

**Comment by NoMoreFood** [comment]
The repository now contains a list of all hashes for the binaries in SHA1, SHA256, and MD5. 
 You can find it here: https://github.com/NoMoreFood/putty-cac/blob/master/binaries/puttycac-hash.txt. 
 I'll reference that list in the next official release note.
