### ISSUE TITLE
multiple certificates on the same card

### ISSUE THREAD

**Issue by cristivulpe** [risacher/putty-cac#30]
I have a card that holds more certificates. The issue I have is that the CAPI menu (presented on the "CAPI configuration" section of the home page) allows me to select only one. Is it any way that I can get more of those certificates (maybe there is a filtering by a certain attribute)?

**Comment by jdantzler** [comment]
You can use pageant instead as it allows more then one CAPI cert.  Right now the current version of PuTTY only allows one CAPI cert.

**Comment by NoMoreFood** [comment]
Closing this one out.  Josh is right - the right way to do this is with pageant.  PuTTY (without pageant) is similarly limited in that it only allows you to specify one key.  That said, I did seriously consider this.  The GUI changes would be easy but the main authentication function in the code would have to be modified significantly to loop through multiple keys and we're trying to keep deltas on top of the upstream release relatively limited so future merges are simpler.
