### ISSUE TITLE
hi, may couse some bad results

### ISSUE THREAD

**Issue by wen1991** [risacher/putty-cac#33]
in sshsh512.c
-uint64 wordblock[16];
+uint64 wordblock[16]={0};

and in SHA512_myINIT
+for(i=0;i<128;i++)
+  	s->block[i] = 0;

i test this case for sha512, but i found my result would be changed when i run it again

**Comment by NoMoreFood** [comment]
@wen1991 I haven't dove into the PuTTY code to validate your concern, but if this is a problem then it's in the upstream PuTTY code, not PuTTY-CAC.  Please reach out to their maintainers of PuTTY and if they made this modification, then we'll incorporate it into PuTTY-CAC.   You can find more information here:  http://www.chiark.greenend.org.uk/~sgtatham/putty/

**Comment by NoMoreFood** [comment]
Per previous comment, there is no action for us here to closing this issue.
