### ISSUE TITLE
sync with putty 0.68

### ISSUE THREAD

**Issue by k3it** [risacher/putty-cac#36]
these features are new in 0.68 (released 2017-02-21):

Security fix: an integer overflow bug in the agent forwarding code. See vuln-agent-fwd-overflow.
Security fix: the Windows PuTTY binaries should no longer be vulnerable to hijacking by specially named DLLs in the same directory (on versions of Windows where they previously were). See vuln-indirect-dll-hijack.
Windows PuTTY no longer sets a restrictive process ACL by default, because this turned out to inconvenience too many legitimate applications such as NVDA and TortoiseGit. You can still manually request a restricted ACL using the command-line option -restrict-acl.
The Windows PuTTY tools now come in a 64-bit version.
The Windows PuTTY tools now have Windows's ASLR and DEP security features turned on.
Support for elliptic-curve cryptography (the NIST curves and 25519), for host keys, user authentication keys, and key exchange.
Support for importing and exporting OpenSSH's new private key format.
Host key preference policy change: PuTTY prefers host key formats for which it already knows the key.
Run-time option (from the system menu / Ctrl-right-click menu) to retrieve other host keys from the same server (which cross-certifies them using the session key established using an already-known key) and add them to the known host-keys database.
The Unix GUI PuTTY tools can now be built against GTK 3.
There is now a Unix version of Pageant.http://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

These features are new in 0.67 (released 2016-03-05):

Security fix: a buffer overrun in the old-style SCP protocol when receiving the header of each file downloaded from the server is fixed. See vuln-pscp-sink-sscanf.
Windows PuTTY now sets its process ACL more restrictively, in an attempt to defend against malicious other processes reading sensitive data out of its memory.
Assorted other robustness fixes for crashes and memory leaks.
We have started using Authenticode to sign our Windows executables and installer.

**Comment by k3it** [comment]
@jdantzler I see your .67 pull request .  Can you please describe the procedure you used for syncing putty-cac with the main putty source code? I'd like to stay current but not sure how to properly merge

**Comment by k3it** [comment]
@jdantzler  @risacher  I  spent some hours trying to understand what needs to be done.   it looks like the code in the official putty 0.68 was refactored, numerous diffs with the 0.67 version.  the pageant code is now split between winpgnt.c and pageant.c (the unix version of the agent).  functions/structures have been renamed/rewritten also,  e.g. in ssh.c.  it does not seem trivial to sync the CAC patches.  Also Simon does not want changes outside of the windows directory, unless it's a cross platform change: https://tartarus.org/~simon/putty-snapshots/htmldoc/AppendixD.html . some talented hacking  needs to take place here :), afraid this is over my head.

**Comment by NoMoreFood** [comment]
@k3it Sensing that Daniel may not have the time to maintain this (based on the lack of attention to Josh's pull request), I created my own release based on 0.68 that also includes Josh's enhancements.  You can find the release at the link below.  Since we're not asking Simon to commit this upstream, I didn't go out of my way to avoid modifying the code in the root directory.  I forked my release from Daniel's repository and submitted a pull request in the event he wants to commit my changes.  Please let me know if you see any issues.  

https://github.com/NoMoreFood/putty-cac/releases/tag/0.68

**Comment by k3it** [comment]
@NoMoreFood thanks for looking at this.  I see a couple of issues. will document  under your repository
