### ISSUE TITLE
Update to 0.70 due to security fixes

### ISSUE THREAD

**Issue by trixpan** [risacher/putty-cac#45]
```
These features are new in 0.70 (released 2017-07-08):

Security fix: the Windows PuTTY binaries should no longer be vulnerable to hijacking by specially named DLLs in the same directory, even a name we missed when we thought we'd fixed this in 0.69. See vuln-indirect-dll-hijack-3.
Windows PuTTY should be able to print again, after our DLL hijacking defences broke that functionality.
Windows PuTTY should be able to accept keyboard input outside the current code page, after our DLL hijacking defences broke that too.
```

**Comment by trixpan** [comment]
Commit suggests version is already merged, however news don't reflect that yet?

> News
> 2017-03-20: Bryan Berns, with help from @jdantzler and @k3it, has updated PuTTY-CAC to sync with the upstream PuTTY 0.68. Since I have been slow in merging the upstream, I recommend that users of PuTTY-CAC pull from his repository: https://github.com/NoMoreFood/putty-cac/releases

**Comment by NoMoreFood** [comment]
Daniel Risacher (@risacher) gave me access to keep his fork in sync with mine, but I don't control the website.  I'll see about asking him to do an HTTP redirect from his PuTTY CAC page to my fork since the usage instructions there are also out of date.

**Comment by risacher** [comment]
@NoMoreFood Already fixed
