### ISSUE TITLE
Putty CAC 0.81 Windows Pageant doesn't have Add CAPI Cert button

### ISSUE THREAD

**Issue by rteske2work** [risacher/putty-cac#49]
@jdantzler Started up the windows executable version of Pageant v0.81 and there's only the Add Key and Remove Key buttons. Add CAPI Cert button is not there. This was already an issue in v0.80.
Is there an update available?

**Comment by rteske2work** [comment]
![image](https://github.com/risacher/putty-cac/assets/163596211/3d3d9d7f-b487-418e-a095-67e834ac85ca)

**Comment by JoshDantzler** [comment]
Please reach out to @NoMoreFood as he is the current/main developer on this now.
His repo can be found here:  
https://github.com/NoMoreFood/putty-cac

**Comment by rteske2work** [comment]
Reaching out to NoMoreFood
