### ISSUE TITLE
Sync with PuTTY 0.64 (was 0.63)

### ISSUE THREAD

**Issue by risacher** [risacher/putty-cac#8]
Sync with PuTTY 0.63

**Comment by LordMike** [comment]
0.65 is now in beta, last release was 2015-07-25.

**Comment by risacher** [comment]
PuTTY-CAC version sync'd to PuTTY-0.65 is available at http://risacher.org/putty-cac/  - will be integrated into the github codebase, although probably not until mid-September.

**Comment by iticory** [comment]
FYI...  If you're like me, the only feature you need from PuTTY-CAC is the ability to use CAPI certificates,

For this all I need is pageant.exe and I just continue to use the mainline version of PuTTY.  Whenever PuTTY releases a new version, I've always been able to upgrade it while keeping my existing pageant.

It's possible this may not always work as PuTTY might release an update that breaks compatibility with older versions of the agent.  However, until that happens there's no need to wait for PuTTY-CAC to catch up if all you need is windows certificate login.

Thank you risacher!

**Comment by YujiXcast** [comment]
+1 for iticory, from user point of view.

However, in original pageant code is not clearly separate from others, putty, puttygen, plink, and so on.  I guess It seems not so easy to cherry pick CAPI deltas only for pageant.

On the other hand, pkcs#11 code in Putty-CAC 0.62 should be erased as Risacher mentioned CAPI is recommended, shouldn't it?

**Comment by YujiXcast** [comment]
How Lovely!

> However, in original putty code pageant is not clearly separate from others, putty, puttygen, plink, and so on. I guess It seems not so easy to cherry pick CAPI deltas only for pageant.

Carelessly, I didn't read README.md and checked http://risacher.org/putty-cac/  . There are zip archives of Josh Dantzler. He did it.

> On the other hand, pkcs#11 code in Putty-CAC 0.62 should be erased as Risacher mentioned CAPI is recommended, shouldn't it?

They already erased pkcs#11 API. :+1: 

Thanks Josh & Risacher.

**Comment by risacher** [comment]
For what it's worth, PKCS#11 support might still be useful to someone...    It would certainly be useful to folks who want to use PuTTY-CAC on non-windows platforms.  I've had at least one request for this.  

Either way, closing this issue.
