### ISSUE TITLE
Autoload CAPI Cert from command line

### ISSUE THREAD

**Issue by McSlow** [risacher/putty-cac#9]
Hi,
short question: is there any way to autoload a capi cert into pageant from command line?
a short attempt to just add "pageant.exe Users/MY/03573151..." (as shown in the key dialog when loaded) to the command line lead to a "couldn't load this key" messagebox. 

best regards,
Björn

**Comment by deejayy** [comment]
According to the source, you must prepend the key with "CAPI:", so pageant.exe CAPI:<key>, but i can put anything in <key>, pageant result in an appcrash.

**Comment by deejayy** [comment]
Wow, got it working with this:
pageant.exe CAPI:User\\\\MY\\\\&lt;hex-key&gt;

**Comment by jdantzler** [comment]
I am also having difficulty making it work.  Is the hex-key the same as the capi key?  This is what I have so far and I still get the error: "Couldn't load this key (unable to open file)

 "C:\Program Files\Putty\pageant.exe"  CAPI:User\\\\MY\\\\<my-capi-key>

**Comment by foulsoft** [comment]
Dear all,

Using http://www.risacher.org/putty-cac/pageant.exe to download CAPI capable pageant from PuTTY-CAC project... I only ask for pageant followed by the CAPI key found using PuTTY... just like....(of course <HexKey> is to be replaced with your actual Hex Key... :)
pageant CAPI:User\MY\<HexKey>

Hope this helps.... Francois.

**Comment by LordMike** [comment]
I'd like this too. :)

**Comment by iticory** [comment]
This already works, but you have to use the hex value of the certificate's thumbprint:

pageant.exe CAPI:User\MY\THUMBPRINT

You can find the thumbprint on the details tab of the "Certificate Details" window.  Just make sure to remove all of the spaces if you copy paste it.

C:\Users\username\Downloads\pageant.exe CAPI:User\MY\cd196a916babfb87adbcd72a3417a1a428d7573c

This works from the command line, but I use it as the target of a windows shortcut in my startup folder and pageant is always ready for me when I log in.

**Comment by YujiXcast** [comment]
As @iticory wrote, I made pageant up with shortcut in my startup folder. It works fine with pageant of putty-cac 0.62.

As @risacher and @jdantzler released 0.65, I tried new pageant. While it works fine with GUI, but cannot append my CAPI entry with CLI options. Pagent makes error dialog "Couldn't load this key (unable to open file)".

**Comment by jdantzler** [comment]
@YujiXcast I have fixed the issue with the CAPI entry not appending automatically.  I will upload the fix to my github page shortly and I will see if I can get @risacher to update his site with the fix as well.

**Comment by IMAI-Yuji** [comment]
Thanks Josh! :smile:

**Comment by YujiXcast** [comment]
Thanks, Josh! :smile:

**Comment by jdantzler** [comment]
@alohaug Original PuTTY-CAC (Pageant) 0.65:  https://github.com/jdantzler/putty-cac/blob/master/executables/pageant.exe?raw=true

This version includes the auto load CAPI key fix.

**Comment by alohaug** [comment]
@jdantzler Yeah, I confirm it works well, again.

**Comment by alohaug** [comment]
Knock, knock.

Do we still have problems with this issue? It seems @McSlow  or @risacher can close.

**Comment by McSlow** [comment]
Hi, thanks a lot, works here too - thanks for the fix.

**Comment by IMAI-Yuji** [comment]
:thumbsup:

**Comment by alohaug** [comment]
:thumbsup:

**Comment by hablutzel1** [comment]
The following post might be of interest for someone trying to do the same thing with PKCS #11 certificates, https://blobfish.pe/blog/load-pkcs-11-key-using-putty-cac-pageant-from-command-line/.
